name: Android CI

on:
  push:
    branches: 
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'
  workflow_dispatch:        
        
permissions:
  contents: write
jobs:
  build:
  

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Git rebase
      run: |
        git rebase origin/master
  
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission to gradlew
      run: |
        chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Push
      run: |
        git push origin master
